name: CI Lint Commit Message
on: [pull_request]

jobs:
  lint-commitmsg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Validate pull request commits with commitlint
        run: npx commitlint --from "${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }}" --to "${{ github.event.pull_request.head.sha }}" --verbose
